site_name: pyadi-jif
site_description: Python interface and configurator for ADI JESD Interface Framework
site_author: Travis F. Collins

#theme: readthedocs
theme:
  name: material
  # logo: imgs/cpu-fill.svg
  logo: imgs/cpu.svg
  # palette:
  #   scheme: slate
  #   primary: deep orange

repo_url: https://github.com/tfcollins/pyadi-jif

pages:
- Home: index.md

nav:
    - Home: index.md
    - Definitions: defs.md
    - Usage Flow: flow.md
    - Data Converters: converters.md
    - Clock Chips: clocks.md
    - FPGAs: fpgas.md
    - Supported Parts: parts.md
    - CLI: cli.md
    - Reference: ref.md
    - Clocks Ref: devs/clocks.md
    - Converters Ref: devs/converters.md
    - JESD Ref: devs/jesd.md

markdown_extensions:
  # - pymdownx.highlight
  # - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings
  - mermaid2
